import PersonImg1 from '../assets/images/person1.png';
import PersonImg2 from '../assets/images/person2.png';
import PersonImg3 from '../assets/images/person3.png';
import PersonImg4 from '../assets/images/person4.png';
import ProjectImg1 from '../assets/images/project1.png';
import ProjectImg2 from '../assets/images/project2.png';

// API of OurTeam

export const dataOurTeam = [
    { id: 1, image: PersonImg1, name_uz: "Jahongir Abduganiyev", name_ru: "Джахангир Абдуганиев", name_en: "Jahangir Abduganiyev", prof_uz: "BiC agentligi asoschisi", prof_ru: "основатель агентства BiC", prof_en: "founder of BiC agency" },
    { id: 2, image: PersonImg2, name_uz: "Rustambek Turobov", name_ru: "Рустамбек Туробов", name_en: "Rustambek Turobov", prof_uz: "SMM menejeri", prof_ru: "SMM менеджер", prof_en: "SMM manager" },
    { id: 3, image: PersonImg3, name_uz: "Diyor Zoyirov", name_ru: "Дияр Зоиров", name_en: "Diyar Zoirov", prof_uz: "loyiha menejeri", prof_ru: "менеджер проекта", prof_en: "project manager" },
    { id: 4, image: PersonImg4, name_uz: "Sardor Kulliev", name_ru: "Сардар Куллиев", name_en: "Sardar Kulliev", prof_uz: "grafik dizayner", prof_ru: "графический дизайнер", prof_en: "graphic designer" },
];

// API of FAQ

export const dataFAQ = [
    { id: 1, question_uz: "Raqamli marketing nima?", question_ru: "Raqamli marketing nima?", question_en: "Raqamli marketing nima?", answer_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!" },
    { id: 2, question_uz: "Raqamli marketingning afzalliklari nimada?", question_ru: "Raqamli marketingning afzalliklari nimada?", question_en: "Raqamli marketingning afzalliklari nimada?", answer_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!" },
    { id: 3, question_uz: "Raqamli marketingni qanday boshlashim mumkin?", question_ru: "Raqamli marketingni qanday boshlashim mumkin?", question_en: "Raqamli marketingni qanday boshlashim mumkin?", answer_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!" },
    { id: 4, question_uz: "SEO va PPC o'rtasidagi farq nima?", question_ru: "SEO va PPC o'rtasidagi farq nima?", question_en: "SEO va PPC o'rtasidagi farq nima?", answer_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!" },
    { id: 5, question_uz: "Kontent marketingi nima?", question_ru: "Kontent marketingi nima?", question_en: "Kontent marketingi nima?", answer_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!", answer_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem iure tenetur, magnam saepe veritatis ad optio placeat nobis. Deleniti, dignissimos! Quisquam voluptatibus ipsa, reiciendis eum est tempore tempora ea!" },
];

// API of Projects

export const dataProjects = [
    { id: 1, image: ProjectImg1, date: "2022 - 2023", name_uz: "Adoro socks’ instagram posts", name_ru: "Adoro socks’ instagram posts", name_en: "Adoro socks’ instagram posts", description_uz: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik.", description_ru: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik.", description_en: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik." },
    { id: 2, image: ProjectImg2, date: "2022 - 2023", name_uz: "Adoro socks’ instagram posts", name_ru: "Adoro socks’ instagram posts", name_en: "Adoro socks’ instagram posts", description_uz: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik.", description_ru: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik.", description_en: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik." },
    { id: 3, image: ProjectImg1, date: "2022 - 2023", name_uz: "Adoro socks’ instagram posts", name_ru: "Adoro socks’ instagram posts", name_en: "Adoro socks’ instagram posts", description_uz: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik.", description_ru: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik.", description_en: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik." },
    { id: 4, image: ProjectImg2, date: "2022 - 2023", name_uz: "Adoro socks’ instagram posts", name_ru: "Adoro socks’ instagram posts", name_en: "Adoro socks’ instagram posts", description_uz: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik.", description_ru: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik.", description_en: "Bizning jamoamiz moda, texnologiya, mehmondo'stlik va boshqalar kabi sohalarda mijozlar uchun ingl. Bundan tashqari, biz sog'liqni saqlashdan moliyalashtirishgacha bo'lgan sohalarda biznes uchun trafikni va ko'rinishni oshiradigan moslashtirilgan raqamli marketing strategiyalarini ishlab chiqdik." },
]